# Page settings
baseurl = "banyolessolidaria.org"
title = "Banyoles Solidaria"
languageCode = "ca-es"
theme = "hugo-elate-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "banyolessolidaria@gmail.com"

  # Navigation
  [params.navigation]
    brand = "Banyoles Solidària"
    intro = "Intro"
    work = "Projectes internacionals"        #  <- format Què fem
    activity = "Projectes locals"       #
    testimonials = "Experiències"
    services = "Què pots fer tu?"
    about = "Qui som?"
    follow = "Segueix-nos"
    contact = "Contacta"
    social = [
        ["icon-feed", "http://banyolessolidaria.blogspot.com/"],
        ["icon-twitter", "https://twitter.com/BanyolesE"],
        ["icon-facebook", "https://ca-es.facebook.com/banyoles.solidaria"]
      ]
      
    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = 'Molta gent petita, en llocs petits, fent petites coses, poden canviar el món 
     <br />*Eduardo Galeano (1940-2015)*'
     Subtitle = 'Web en construcció'



# Intro section (Secció seguexe'ns)
# Available icons: http://simplelineicons.com/
  [params.intro]
    enable = false
    title = "Intro"
    
    [[params.intro.item]]
      title = "Blog"
      description = "En el blog trobaràs la nostra activitat quotidiana relacionada amb els projectes de desenvolupament i també la nostra implicació en el món que ens envolta."
      url = "http://banyolessolidaria.blogspot.com/"
      button = "Segueix-nos"
      icon = "icon-feed"
      img = "img_7.jpg"

    [[params.intro.item]]
      title = "Facebook"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://ca-es.facebook.com/banyoles.solidaria"
      button = "Segueix-nos"
      icon = "icon-facebook"
      img = "img_8.jpg"

    [[params.intro.item]]
      title = "Twitter"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://twitter.com/BanyolesE"
      button = "Segueix-nos"
      icon = "icon-twitter"
      img = "img_10.jpg"

    [params.intro.video]
      enable = false
      title = "Watch the video"
      icon = "icon-play2"
      url = "https://vimeo.com/channels/staffpicks/93951774"
      
  # Work section
  [params.work]
    enable = true
    title = "Els nostres projectes internacionals"
    description = "Hi tenim projectes en marxa. Exactament,  a Condega (Nicaragua), Segundo Montes (El Salvador) i Kerewan (Gàmbia), en diferents camps de la cooperació: Educatius: construccions d’escoles, beques escolars i donació de material escolar i esportiu.Desenvolupament agrari: microcrèdits, donació de maquinària, regadius, molins fariners, dipòsits per al gra, donació d’adobs i llavors...Serveis socials: Atenció a nens de carrer, transport comunitari, apadrinament de nens discapacitats i avis desemparats, ajuda d’emergència...Atenció sanitària: Construcció i dotació d’un dispensari, tramesa de medicaments, formació de personal sanitari."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "logo.png"
      alt = "Image2"
      title = "El Salvador"
      subtitle = "Segundo Montes"
      
    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Nicaragua"
      subtitle = "Condega"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Gàmbia"
      subtitle = "Kerewan-Nyakoy i Share Yewto"

  # Activities section
  [params.activity]
    enable = true
    title = "Què fem?"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.activity.row]]
      img = "logo.png"
      alt = "Image2"
      title = "Project 1"
      subtitle = "[Far](dar) far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.activity.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.activity.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"


  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Experiències"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"

  # Services section
  [params.services]
    enable = true
    title = "Què pots fer tu?"
    description = "Tu ens pots ajudar a fer molt més"

    [[params.services.item]]
      title = "Difusió dels nostres projectes"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Participació en les nostres reunions"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Participació en les nostres activitats"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "Fes un donatiu"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-monitor"
      
      [[params.services.item]]
      title = "Fes-te soci"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Qui som?"
    description = "BANYOLES SOLIDÀRIA és una ONG que, des de 1994, treballa i potencia la solidaritat entre les persones, pobles i cultures.Som un grup de gent diversa i ideològicament plural, que no es conforma a sentir parlar de la pobresa dels pobles del Sud, sinó que actua per a combatre-la. Pretenem impulsar la cooperació solidària amb els països del Sud, fomentar els agermanaments de la comarca amb Condega, la Comunidad Segundo Montes i Kerewan, col·laborar en actuacions humanitàries i d’emergència i sensibilitzar la població dels problemes de la pobresa"
    
    [[params.about.item]]
      name = "Martí Jutglar"
      position = "President"
      img = "person1.jpg"
      alt = "Person1"
      #social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
      #  ["icon-linkedin", "#"]
      #]

    [[params.about.item]]
      name = "Àlex Garcia"
      position = "Secretari"
      description = "Professor jubilat, enamorat de l’Estany i ciutadà d'un món que voldria sense fronteres !!"
      img = "person2.jpg"
      alt = "Person2"
     

    [[params.about.item]]
      name = "Ramon Caralt"
      position = "Tresorer"
      description = "Enginyer jubilat. Implicat en temes ecològics i solidaris"
      img = "person3.jpg"
      alt = "Person3"
     

    [[params.about.item]]
      name = "Carme Gubert"
      position = "Vocal"
      description = "Mare, mestra i militant de causes perdudes. Crec en les persones i espero un futur millor"
      img = "person3.jpg"
      alt = "Person3"
      
    [[params.about.item]]
      name = "Marta Casanovas"
      position = "Vocal"
      description = "Sector turístic. Jubilada. Crec que, fent un petit esforç aquí, podem ajudar molt els pobles germans."
      img = "person3.jpg"
      alt = "Person3"
      
      [[params.about.item]]
      name = "Lola Torrent"
      position = "Vocal"
      description = "Interessada per la natura, per la cultura, pel món en general. Totes les persones anem al mateix vaixell, però no sembla que ens en fem càrrec. Temps d'arremangar-se!"
      img = "person3.jpg"
      alt = "Person3"
  
     [[params.about.item]]
      name = "Anna Lietz"
      position = "Vocal"
      description = "Actuo amb solidaritat perquè veig moltes injustícies al món.  Estic agraïda que no he de lluitar per sobreviure"
      img = "person3.jpg"
      alt = "Person3"
  
  [params.follow]
    enable = false
    title = "Segueix-nos"
    
    [[params.follow.item]]
      title = "Blog"
      description = "En el blog trobaràs la nostra activitat quotidiana relacionada amb els projectes de desenvolupament i també la nostra implicació en el món que ens envolta."
      url = "http://banyolessolidaria.blogspot.com/"
      button = "Segueix-nos"
      icon = "icon-feed"
      img = "img_7.jpg"

    [[params.follow.item]]
      title = "Facebook"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://ca-es.facebook.com/banyoles.solidaria"
      button = "Segueix-nos"
      icon = "icon-facebook"
      img = "img_8.jpg"

    [[params.follow.item]]
      title = "Twitter"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://twitter.com/BanyolesE"
      button = "Segueix-nos"
      icon = "icon-twitter"
      img = "img_10.jpg"

    [params.follow.video]
      enable = false
      title = "Watch the video"
      icon = "icon-play2"
      url = "https://vimeo.com/channels/staffpicks/93951774"

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Contacta"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Carrer de Barcelona, 54 (centre cívic), 17820 Banyoles"],
        ["icon-phone", "972 572 262"],
        ["icon-envelope", "banyolessolidaria@gmail.com"],
        ["icon-globe", '<a href="http://banyolessolidaria.org/" target="_blank">banyolessolidaria.org</a>']
      ]

    name = "Nom"
    email = "Correu electrònic"
    phone = "Telèfon"
    message = "Missatge"
    button = "Enviar missatge"

  # # Footer section
  # [params.footer]
  #   enable = true
  #   copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
  #   links = [
  #       ["icon-facebook", "https://ca-es.facebook.com/banyoles.solidaria"]
  #     ]
