# Configuració
baseurl = "banyolessolidaria.org"
title = "Banyoles Solidaria"
languageCode = "ca-es"
theme = "hugo-elate-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[markup.goldmark.renderer]
unsafe= true

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Informació
  author = ""
  description = ""
  email = "banyolessolidaria@gmail.com"

  # Barra de navegació
  [params.navigation]
    brand = "Banyoles Solidària"
    intro = "Intro"
    
    about =  "Qui som?" 
    activity =  "Què fem?" 
    services = "Què pots fer tu?"
    
    contact = "Contacta'ns!"
    social = [
        ["icon-feed", "http://banyolessolidaria.blogspot.com/"],
        ["icon-twitter", "https://twitter.com/BanyolesE"],
        ["icon-facebook", "https://ca-es.facebook.com/banyoles.solidaria"],
        ["icon-notebook", "https://drive.google.com/file/d/0Byanl5FeJxT2Y0taNVNkaFlhQ2U3VUFHVm9acXExVVp4Q21n/view"]
      ]
  # Icones disponibles https://docdock.netlify.com/shortcodes/icon/
  # Secció inicial
  [params.hero]
    title = "![Banyoles Solidària](images/logo_ovalat.png)<br />ORGANITZACIÓ NO GOVERNAMENTAL PER AL DESENVOLUPAMENT"
    Subtitle = "Molta gent petita, en llocs petits, fent petites coses, poden canviar el món<br />*Eduardo Galeano (1940-2015)*"
	
# About section
  [params.about]
    enable = true
    title = "Qui som?"
    description = "BANYOLES SOLIDÀRIA és una ONG que, des de 1994, treballa i potencia la solidaritat entre les persones, pobles i cultures.Som un grup de gent diversa i ideològicament plural, que no es conforma a sentir parlar de la pobresa dels pobles del Sud, sinó que actua per a combatre-la. Pretenem impulsar la cooperació solidària amb els països del Sud, fomentar els agermanaments de la comarca amb Condega, la Comunidad Segundo Montes i Kerewan, col·laborar en actuacions humanitàries i d’emergència i sensibilitzar la població dels problemes de la pobresa"
    
    [[params.about.item]]
      name = "Martí Jutglar"
      position = "President"
      description = "<br/><br/><br/>"
      img = "people/Martí Jutglar2.jpg"
      alt = "Person1"
      #social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
      #  ["icon-linkedin", "#"]
      #]

    
     
	[[params.about.item]]
      name = "Carme Gubert"
      position = "Secretària"
      description = "Mare, mestra i militant de causes perdudes. Crec en les persones i espero un futur millor<br/><br/><br/>"
      img = "people/Carme Gubert.jpg"
      alt = "Person3"
      
    [[params.about.item]]
      name = "Ramon Caralt"
      position = "Tresorer"
      description = "Enginyer jubilat. Implicat en temes ecològics i solidaris<br/><br/>"
      img = "people/Ramon Caralt.jpg"
      alt = "Person3"
     
	[[params.about.item]]
      name = "Àlex Garcia"
      position = "Vocal"
      description = "Professor jubilat, enamorat de l’Estany i ciutadà d'un món que voldria sense fronteres !!"
      img = "people/Alex García.JPG"
      alt = "Person2"
    
    [[params.about.item]]
      name = "Marta Casanovas"
      position = "Vocal"
      description = "Sector turístic. Jubilada. Crec que, fent un petit esforç aquí, podem ajudar molt els pobles germans.<br/><br/><br/>"
      img = "people/Marta Casanovas.jpg"
      alt = "Person3"
      
      [[params.about.item]]
      name = "Lola Torrent"
      position = "Vocal"
      description = "Interessada per la natura, per la cultura, pel món en general. Totes les persones anem al mateix vaixell, però no sembla que ens en fem càrrec. Temps d'arremangar-se!"
      img = "people/Lola Torrent.jpg"
      alt = "Person3"

      [[params.about.item]]
      name = "Dolors Terradas"
      position = "Vocal"
      description = ""
      img = "people/Dolors Terradas.jpg"
      alt = "Person3"
      
     [[params.about.item]]
      name = "Anna Lietz"
      position = "Vocal"
      description = "Actuo amb solidaritat perquè veig moltes injustícies al món.  Estic agraïda que no he de lluitar per sobreviure"
      img = "people/Ana Lietz.jpg"
      alt = "Person3"
      
     [[params.about.item]]
      name = "Wolfram Lietz"
      position = "Vocal"
      description = "Tots som veïns<br/><br/><br/><br/>"
      img = "people/Wolf Lietz.jpg"
      alt = "Person3"
      
     [[params.about.item]]
      name = "Maria Garcia"
      position = "Vocal"
      description = "<br/><br/><br/><br/>"
      img = "people/mgarcia.jpg"
      alt = "Person3"
      
      
     [[params.about.item]]
      name = "Miquel Miras"
      position = "Vocal"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      
      
     [[params.about.item]]
      name = "Maran Gri Maureta"
      position = "Vocal"
      description = " "
      img = "people/Maran Gri3.jpg"
      alt = "Person3"
      
      
     [[params.about.item]]
      name = "Josep Callís i Franco"
      position = "Vocal"
      description = " "
      img = "person3.jpg"
      alt = "Person3"
	  
  # Activities section
  [params.activity]
    enable = true
    title = "Què fem?"
    description = "Les nostres activitats locals arriben ben lluny i connecten amb els nostres projectes internacionals"

    local = 'Què fem a la comarca?'

  # who section: qui som?
  [params.international]
    title = "Què fem als pobles germans?"
    description = "Hi tenim projectes en marxa. Exactament,  a Condega (Nicaragua), Segundo Montes (El Salvador) i Kerewan (Gàmbia), en diferents camps de la cooperació: Educatius: construccions d’escoles, beques escolars i donació de material escolar i esportiu.Desenvolupament agrari: microcrèdits, donació de maquinària, regadius, molins fariners, dipòsits per al gra, donació d’adobs i llavors...Serveis socials: Atenció a nens de carrer, transport comunitari, apadrinament de nens discapacitats i avis desemparats, ajuda d’emergència...Atenció sanitària: Construcció i dotació d’un dispensari, tramesa de medicaments, formació de personal sanitari."

    [[params.international.row]]
      img = "mapa_el_salvador.jpg"
      alt = "Image2"
      title = "El Salvador"
      doc = "salvador"
      subtitle = "Treballem en el departament de Morazán (el més pobre del país), a Meanguera, i a diversos municipis del Nord de Morazán i, especialment, a la comunitat Segundo Montes, creada el 1990 per refugiats repratiats, un cop acabada la cruenta guerra civil salvadorenca. Treballem en projectes educatius, agrícoles i d'empoderament de les dones."
      
    [[params.international.row]]
      img = "mapa_nicaragua.jpg"
      alt = "Image2"
      title = "Nicaragua"
      doc = "nicaragua"
      subtitle = "Condega, municipi al nord del país, d'uns 30.000 habitants, té un nucli urbà i unes 66 comunitats rurals, on la població treballa al camp com a petits propietaris o jornalers. Hi predomina la població jove, que no troba feina qualificada. Els projectes que portem a terme són de caire educatiu, d'empoderament d'adolescents i de desenvolupament cooperatiu."

    [[params.international.row]]
      img = "mapa_gambia.jpg"
      alt = "Image3"
      title = "Gàmbia"
      doc  = "gambia"
      subtitle = "Des de l’any 94 col·laborem amb un poble del centre de Gàmbia anomenat Kerewan. A l’any 2018, a instàncies de l’Ajuntament de Banyoles hem ampliat la nostra actuació a un nou poble, també a l’interior del país, anomenat Sare Yewtou.Treballem sobretot en desenvolupament rural, principalment en la millora de la collita per propiciar la millora en l’alimentació."
    
  # who section: qui som?
  [params.local]
    title = "Què fem a la comarca?"
    description = "Les nostres activitats locals arriben ben lluny i connecten amb els nostres projectes internacionals."

   [[params.local.row]]
      img = "act_denuncia.jpg"
      alt = "Image2"
      doc = "activity01"
      title = "Activitats de denúncia i sensibilització"
      subtitle = "Xerrades, exposicions, documentals..."

    [[params.local.row]]
      img = "act_recaptar.jpg"
      alt = "Image2"
      doc = "activity02"      
      title = "Activitats per donar a conèixer Banyoles Solidària i recaptar fons"
      subtitle = "Parades d’artesania, rifes, festes, concerts..."

    [[params.local.row]]
      img = "act_denuncia_local.jpg"
      alt = "Image3"
      doc = "activity03"      
      title = "Activitats de denúncia i sensibilització amb altres entitats del Pla de l’Estany"
      subtitle = "Comerç responsable, ecologia, apoderament de la dona, suport als refugiats. "

  # Services section
  [params.services]
    enable = true
    title = "Què pots fer tu?"
    description = "Tu ens pots ajudar a fer molt més"

    [[params.services.item]]
      title = "Participa en les nostres reunions"
      description = "Cada 1er i 3er dimarts de cada mes, de 8 a  2 ⁄ 4  de 10 del vespre, ens reunim al Centre Cívic de Banyoles, carrer Barcelona 54, al barri de la Farga."
      icon = "icon-users"
      
    [[params.services.item]]
      title = "Fes-te persona voluntària"
      description = "Participa en les nostres activitats. Durant l’any fem algunes activitats de denúncia,  de sensibilització o per recaptar fons i qualsevol ajuda de tota mena hi serà benvinguda! També és molt important que ens ajudis a fer difusió d’aquests actes."
      icon = "icon-list-ul"

      [[params.services.item]]
      title = "Apadrina"
      description = "Tens l´oportunitat de ser padrí d'un infant amb alguna discapacitat. També pots esdevenir una gran ajuda per pagar els estudis dels joves dels pobles germans."
      icon = "icon-link"
      
      [[params.services.item]]
      title = "Fes-te soci"
      description = "Si no tens temps però sents propera la tasca que anem desenvolupant, pots fer aportacions econòmiques amb la modalitat que et sigui més còmoda: una aportació mensual, trimestral o anual. O puntual. Rebràs el certificat de la teva donació per presentar juntament amb la declaració de renda."
      icon = "icon-user-plus"
  
  [params.follow]
    enable = false
    title = "Segueix-nos"
    
    [[params.follow.item]]
      title = "Blog"
      description = "En el blog trobaràs la nostra activitat quotidiana relacionada amb els projectes de desenvolupament i també la nostra implicació en el món que ens envolta."
      url = "http://banyolessolidaria.blogspot.com/"
      button = "Segueix-nos"
      icon = "icon-feed"
      img = "img_7.jpg"

    [[params.follow.item]]
      title = "Facebook"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://ca-es.facebook.com/banyoles.solidaria"
      button = "Segueix-nos"
      icon = "icon-facebook"
      img = "img_8.jpg"

    [[params.follow.item]]
      title = "Twitter"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://twitter.com/BanyolesE"
      button = "Segueix-nos"
      icon = "icon-twitter"
      img = "img_10.jpg"

    [params.follow.video]
      enable = false
      title = "Watch the video"
      icon = "icon-play2"
      url = "https://vimeo.com/channels/staffpicks/93951774"
	
  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Contacta amb nosaltres"
    description = "Estarem molt contents de contestar-te quan et posis en contacte amb nosaltres a través del correu o d’aquesta mateixa pàgina. Mirarem de solucionar-te les teves demandes."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Carrer de Barcelona, 54 (centre cívic), 17820 Banyoles"],
        ["icon-phone", "972 572 262"],
        ["icon-envelope", "banyolessolidaria@gmail.com"],
        ["icon-globe", '<a href="http://banyolessolidaria.org/" target="_blank">banyolessolidaria.org</a>']
      ]

    name = "Nom"
    email = "Correu electrònic"
    phone = "Telèfon"
    message = "Missatge"
    button = "Enviar missatge"
	
	
  # Footer section
  [params.footer]
    enable = true
    copyright = 'Col·laboradors:'
	
    collaborators = [
    "Ajuntament Banyoles .jpg", 
    "camos_200_150.jpg",
    "cornella_terri_200_150.jpg",
    "foncoberta_200_150.jpg",
    "palol_revardit_200_150.jpg",
    "porqueres_200_150.jpg",
    "serinya_200_150.jpg",
	"Ajuntament Crespià.jpg",
	"Ajuntament Sant Miquel de Campmajor.jpg",
	"Ajuntament vilademuls.jpg",
	"Ajuntaments Esponellà.jpg"]
	privacity="<br><b>AVÍS DE PRIVACITAT DE L’ ASSOCIACIÓ BANYOLES SOLIDÀRIA</b>"
	privacity2="<FONT SIZE=2.5>La visita a la present web www.banyolessolidaria.org no suposa que l'usuari estigui obligat a facilitar cap informació personal. En el cas que l'usuari faciliti alguna informació de caràcter personal, les dades recollides en aquest portal web seran tractades de conformitat amb el Reglament (UE) 2016/679 del Parlament i del Consell de 27 d'Abril de 2016 (en endavant RGPD) i la Llei orgànica 3/2018, de 5 de desembre (en endavant LOPD-GDD). <br>De les dades facilitades pels usuaris en serà Responsable del Tractament l’ASSOCIACIÓ BANYOLES SOLIDÀRIA. En aquest sentit, hem realitzat i mantenim actualitzat el corresponent registre de tractament sobre les dades personals que vostè faciliti a la present web.Els usuaris que facilitin dades de caràcter personal, consenten de manera expressa i inequívocament al tractament de les seves dades per l’ASSOCIACIÓ BANYOLES SOLIDÀRIA, amb la finalitat de respondre a les preguntes que se'ns formulin i/o informar de les nostres activitats. En aquest sentit, es conservaran les dades durant els terminis legals establerts. Les dades recollides no seran objecte de cessió tret que prèviament s'obtingui el consentiment de l'interessat, tret d’obligació legal o en cas de que fos necessari per realitzar les activitats o donacions corresponents. <br>De conformitat amb el previst en la normativa sobre Protecció de Dades Personals, l’ASSOCIACIÓ BANYOLES SOLIDÀRIA ha adoptat les mesures de seguretat adequades i ha instal·lat els mitjans i mesures tècniques necessàries per evitar la pèrdua, mal ús, alteració, tractament o accés no autoritzat a les bases de dades i el robatori de les dades personals. Així mateix, es compromet a notificar, dins del termini establert, qualsevol intromissió que afecti al tractament. <br>En qualsevol moment, l’usuari tindrà la possibilitat d’exercir els drets d’accés, rectificació, oposició, supressió, limitació i portabilitat previstos al RGPD i LOPD-GDD. A tal efecte, l’usuari podrà contactar amb l’ ASSOCIACIÓ BANYOLES SOLIDÀRIA enviant un correu electrònic a l’adreça banyolessolidaria@gmail.com<br>En la sol·licitud hauran de figurar: el nom complet de l'usuari, numero del DNI/NIE/Passaport i fotocopia i descripció del dret exercitat; comprometent-se l’ASSOCIACIÓ BANYOLES SOLIDÀRIA a contestar en el termini legal previst. <br>Així mateix, en el supòsit de voler obtenir més informació no dubti a contactar amb nosaltres a través del correu electrònic banyolessolidaria@gmail.com i ampliarem la informació que consideri oportú."
    #links = [
    #    ["icon-facebook", "https://ca-es.facebook.com/banyoles.solidaria"]
    #  ]/tt