# Configuració

baseurl = "banyolessolidaria.org"
title = "Banyoles Solidaria"
languageCode = "ca-es"
theme = "hugo-elate-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Informació
  author = ""
  description = ""
  email = "banyolessolidaria@gmail.com"

  # Barra de navegació
  [params.navigation]
    brand = "Banyoles Solidària"
    intro = "Intro"
    
    about =  "Qui som?" 
    activity =  "Què fem?" 
    services = "Què pots fer tu?"
    
    contact = "Contacta'ns!"
    social = [
        ["icon-feed", "http://banyolessolidaria.blogspot.com/"],
        ["icon-twitter", "https://twitter.com/BanyolesE"],
        ["icon-facebook", "https://ca-es.facebook.com/banyoles.solidaria"],
        ["icon-notebook", "http://butlleti"]
      ]
  # Icones disponibles https://docdock.netlify.com/shortcodes/icon/
  # Secció inicial
  [params.hero]
    title = '![Banyoles Solidària](images/logo_ovalat_25anys.png)<br/>ORGANITZACIÓ NO GOVERNAMENTAL PER AL DESENVOLUPAMENT</br>(Web en construcció)'
    Subtitle = 'Molta gent petita, en llocs petits, fent petites coses, poden canviar el món <br />*Eduardo Galeano (1940-2015)*'


# About section
  [params.about]
    enable = true
    title = "Qui som?"
    description = "BANYOLES SOLIDÀRIA és una ONG que, des de 1994, treballa i potencia la solidaritat entre les persones, pobles i cultures.Som un grup de gent diversa i ideològicament plural, que no es conforma a sentir parlar de la pobresa dels pobles del Sud, sinó que actua per a combatre-la. Pretenem impulsar la cooperació solidària amb els països del Sud, fomentar els agermanaments de la comarca amb Condega, la Comunidad Segundo Montes i Kerewan, col·laborar en actuacions humanitàries i d’emergència i sensibilitzar la població dels problemes de la pobresa"
    
    [[params.about.item]]
      name = "Martí Jutglar"
      position = "President"
      img = "person1.jpg"
      alt = "Person1"
      #social = [
      #  ["icon-twitter", "#"],
      #  ["icon-facebook", "#"],
      #  ["icon-linkedin", "#"]
      #]

    [[params.about.item]]
      name = "Àlex Garcia"
      position = "Secretari"
      description = "Professor jubilat, enamorat de l’Estany i ciutadà d'un món que voldria sense fronteres !!"
      img = "people/Alex García.JPG"
      alt = "Person2"
     

    [[params.about.item]]
      name = "Ramon Caralt"
      position = "Tresorer"
      description = "Enginyer jubilat. Implicat en temes ecològics i solidaris"
      img = "people/Ramon Caralt.jpg"
      alt = "Person3"
     

    [[params.about.item]]
      name = "Carme Gubert"
      position = "Vocal"
      description = "Mare, mestra i militant de causes perdudes. Crec en les persones i espero un futur millor"
      img = "people/Carme Gubert.jpg"
      alt = "Person3"
      
    [[params.about.item]]
      name = "Marta Casanovas"
      position = "Vocal"
      description = "Sector turístic. Jubilada. Crec que, fent un petit esforç aquí, podem ajudar molt els pobles germans."
      img = "people/Marta Casanovas.jpg"
      alt = "Person3"
      
      [[params.about.item]]
      name = "Lola Torrent"
      position = "Vocal"
      description = "Interessada per la natura, per la cultura, pel món en general. Totes les persones anem al mateix vaixell, però no sembla que ens en fem càrrec. Temps d'arremangar-se!"
      img = "people/Lola Torrent.jpg"
      alt = "Person3"
  
     [[params.about.item]]
      name = "Anna Lietz"
      position = "Vocal"
      description = "Actuo amb solidaritat perquè veig moltes injustícies al món.  Estic agraïda que no he de lluitar per sobreviure"
      img = "people/Ana Lietz.jpg"
      alt = "Person3"
      
     [[params.about.item]]
      name = "Wolfram Lietz"
      position = "Vocal"
      description = "Tots som veïns"
      img = "people/Wolf Lietz.jpg"
      alt = "Person3"
      
     [[params.about.item]]
      name = "Maria Garcia"
      position = "Vocal"
      description = ""
      img = "people/mgarcia.jpg"
      alt = "Person3"
      
      
     [[params.about.item]]
      name = "Miquel Miras"
      position = "Vocal"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      
      
     [[params.about.item]]
      name = "Maran Gri Maureta"
      position = "Vocal"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      
      
     [[params.about.item]]
      name = "Josep Callís i Franco"
      position = "Vocal"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      
      
     [[params.about.item]]
      name = "Adam Pinsach Boix"
      position = "Vocal"
      description = ""
      img = "person3.jpg"
      alt = "Person3"
      
      
     [[params.about.item]]
      name = "Francisca Espinosa Casanova"
      position = "Vocal"
      description = ""
      img = "person3.jpg"
      alt = "Person3"

     
  # Activities section
  [params.activity]
    enable = true
    title = "Què fem?"
    description = "Les nostres activitats locals arriben ben lluny i connecten amb els nostres projectes internacionals"

    local = 'Què fem a la comarca?'

  # who section: qui som?
  [params.international]
    title = "Què fem als pobles germans?"
    description = "Hi tenim projectes en marxa. Exactament,  a Condega (Nicaragua), Segundo Montes (El Salvador) i Kerewan (Gàmbia), en diferents camps de la cooperació: Educatius: construccions d’escoles, beques escolars i donació de material escolar i esportiu.Desenvolupament agrari: microcrèdits, donació de maquinària, regadius, molins fariners, dipòsits per al gra, donació d’adobs i llavors...Serveis socials: Atenció a nens de carrer, transport comunitari, apadrinament de nens discapacitats i avis desemparats, ajuda d’emergència...Atenció sanitària: Construcció i dotació d’un dispensari, tramesa de medicaments, formació de personal sanitari."

    [[params.international.row]]
      img = "mapa_el_salvador.jpg"
      alt = "Image2"
      title = "El Salvador"
      subtitle = "Segundo Montes"
      
    [[params.international.row]]
      img = "mapa_nicaragua.jpg"
      alt = "Image2"
      title = "Nicaragua"
      subtitle = "Condega"

    [[params.international.row]]
      img = "mapa_gambia.jpg"
      alt = "Image3"
      title = "Gàmbia"
      subtitle = "Des de l’any 94 col·laborem amb un poble del centre de Gàmbia anomenat Kerewan. A l’any 2018, a instàncies de l’Ajuntament de Banyoles hem ampliat la nostra actuació a un nou poble, també a l’interior del país, anomenat Sare Yewtou.Treballem sobretot en desenvolupament rural, principalment en la millora de la collita per propiciar la millora en l’alimentació."
    
  # who section: qui som?
  [params.local]
    title = "Què fem a la comarca?"
    description = "Les nostres activitats locals arriben ben lluny i connecten amb els nostres projectes internacionals."

   [[params.local.row]]
      img = "logo.png"
      alt = "Image2"
      title = "Activitats de denúncia i sensibilització"
      subtitle = "Xerrades, exposicions, documentals..."

    [[params.local.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Activitats per donar a conèixer Banyoles Solidària i recaptar fons"
      subtitle = "Parades d’artesania, rifes, festes, concerts..."

    [[params.local.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Activitats de denúncia i sensibilització amb altres entitats del Pla de l’Estany"
      subtitle = "Comerç responsable, ecologia, apoderament de la dona, suport als refugiats. "

  # Services section
  [params.services]
    enable = true
    title = "Què pots fer tu?"
    description = "Tu ens pots ajudar a fer molt més"

    [[params.services.item]]
      title = "Participa en les nostres reunions"
      description = "Cada 2n i 4t dimarts de cada mes, de 8 a 2/4 de 10 del vespre, ens reunim al Centre Cívic de Banyoles, carrer Barcelona 54, al barri de la Farga."
      icon = "icon-users"
      
    [[params.services.item]]
      title = "Fes-te persona voluntària"
      description = "Participa en les nostres activitats. Durant l’any fem algunes activitats de denúncia,  de sensibilització o per recaptar fons i qualsevol ajuda de tota mena hi serà benvinguda! També és molt important que ens ajudis a fer difusió d’aquests actes."
      icon = "icon-list-ul"

      [[params.services.item]]
      title = "Apadrina"
      description = "Tens l´oportunitat de ser padrí d'un infant amb alguna discapacitat. També pots esdevenir una gran ajuda per pagar els estudis dels joves dels pobles germans."
      icon = "icon-link"
      
      [[params.services.item]]
      title = "Fes-te soci"
      description = "Si no tens temps però sents propera la tasca que anem desenvolupant, pots fer aportacions econòmiques amb la modalitat que et sigui més còmoda: una aportació mensual, trimestral o anual. O puntual. Rebràs el certificat de la teva donació per presentar juntament amb la declaració de renda."
      icon = "icon-user-plus"
  
  [params.follow]
    enable = false
    title = "Segueix-nos"
    
    [[params.follow.item]]
      title = "Blog"
      description = "En el blog trobaràs la nostra activitat quotidiana relacionada amb els projectes de desenvolupament i també la nostra implicació en el món que ens envolta."
      url = "http://banyolessolidaria.blogspot.com/"
      button = "Segueix-nos"
      icon = "icon-feed"
      img = "img_7.jpg"

    [[params.follow.item]]
      title = "Facebook"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://ca-es.facebook.com/banyoles.solidaria"
      button = "Segueix-nos"
      icon = "icon-facebook"
      img = "img_8.jpg"

    [[params.follow.item]]
      title = "Twitter"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://twitter.com/BanyolesE"
      button = "Segueix-nos"
      icon = "icon-twitter"
      img = "img_10.jpg"

    [params.follow.video]
      enable = false
      title = "Watch the video"
      icon = "icon-play2"
      url = "https://vimeo.com/channels/staffpicks/93951774"

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Contacta amb nosaltres"
    description = "Estarem molt contents de contestar-te quan et posis en contacte amb nosaltres a través del correu o d’aquesta mateixa pàgina. Mirarem de solucionar-te les teves demandes."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Carrer de Barcelona, 54 (centre cívic), 17820 Banyoles"],
        ["icon-phone", "972 572 262"],
        ["icon-envelope", "banyolessolidaria@gmail.com"],
        ["icon-globe", '<a href="http://banyolessolidaria.org/" target="_blank">banyolessolidaria.org</a>']
      ]

    name = "Nom"
    email = "Correu electrònic"
    phone = "Telèfon"
    message = "Missatge"
    button = "Enviar missatge"

  # Footer section
  [params.footer]
    enable = true
    copyright = 'Col·laboradors:'
    collaborators = [
    "banyoles_200_150.jpg", 
    "camos_200_150.jpg",
    "cornella_terri_200_150.jpg",
    "foncoberta_200_150.jpg",
    "palol_revardit_200_150.jpg",
    "porqueres_200_150.jpg",
    "serinya_200_150.jpg" ]
    #links = [
    #    ["icon-facebook", "https://ca-es.facebook.com/banyoles.solidaria"]
    #  ]
