# Intro section (Secció seguexe'ns)
# Available icons: http://simplelineicons.com/
  [params.intro]
    enable = false
    title = "Intro"
    
    [[params.intro.item]]
      title = "Blog"
      description = "En el blog trobaràs la nostra activitat quotidiana relacionada amb els projectes de desenvolupament i també la nostra implicació en el món que ens envolta."
      url = "http://banyolessolidaria.blogspot.com/"
      button = "Segueix-nos"
      icon = "icon-feed"
      img = "img_7.jpg"

    [[params.intro.item]]
      title = "Facebook"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://ca-es.facebook.com/banyoles.solidaria"
      button = "Segueix-nos"
      icon = "icon-facebook"
      img = "img_8.jpg"

    [[params.intro.item]]
      title = "Twitter"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
      url = "https://twitter.com/BanyolesE"
      button = "Segueix-nos"
      icon = "icon-twitter"
      img = "img_10.jpg"

    [params.intro.video]
      enable = false
      title = "Watch the video"
      icon = "icon-play2"
      url = "https://vimeo.com/channels/staffpicks/93951774"

  # Activities section
  [params.activity_prev]
    enable = true
    title = "Projectes locals"
    description = "Les nostres activitats locals arriben ben lluny i connecten amb els nostres projectes internacionals"
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.activity_prev.row]]
      img = "logo.png"
      alt = "Image2"
      title = "Activitats de denúncia i sensibilització"
      subtitle = "Design"

    [[params.activity_prev.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Activitats per donar a conèixer Banyoles Solidària i recaptar fons"
      subtitle = "Design"

    [[params.activity_prev.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Activitats de denúncia i sensibilització amb altres entitats del Pla de l’Estany"
      subtitle = "Design"
      


  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Experiències"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"

  # who section: qui som?
  [params.work]
    enable = true
    title = "Els nostres projectes internacionals"
    description = "Hi tenim projectes en marxa. Exactament,  a Condega (Nicaragua), Segundo Montes (El Salvador) i Kerewan (Gàmbia), en diferents camps de la cooperació: Educatius: construccions d’escoles, beques escolars i donació de material escolar i esportiu.Desenvolupament agrari: microcrèdits, donació de maquinària, regadius, molins fariners, dipòsits per al gra, donació d’adobs i llavors...Serveis socials: Atenció a nens de carrer, transport comunitari, apadrinament de nens discapacitats i avis desemparats, ajuda d’emergència...Atenció sanitària: Construcció i dotació d’un dispensari, tramesa de medicaments, formació de personal sanitari."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "logo.png"
      alt = "Image2"
      title = "El Salvador"
      subtitle = "Segundo Montes"
      
    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Nicaragua"
      subtitle = "Condega"

    [[params.work.row]]
      img = "gambia.jpg"
      alt = "Image3"
      title = "Gàmbia"
      subtitle = "Des de l’any 94 col·laborem amb un poble del centre de Gàmbia anomenat Kerewan. A l’any 2018, a instàncies de l’Ajuntament de Banyoles hem ampliat la nostra actuació a un nou poble, també a l’interior del país, anomenat Sare Yewtou.Treballem sobretot en desenvolupament rural, principalment en la millora de la collita per propiciar la millora en l’alimentació."
